#!/bin/sh

prefix="/opt/macuim"
top=`pwd`
dest="${top}/../../Package/dest"

if [ ! -d ${prefix}/include ]; then
    sudo mkdir ${prefix}/include
fi
if [ ! -d ${prefix}/lib ]; then
    sudo mkdir ${prefix}/lib
fi

PATH="${prefix}/bin:/bin:/bin:/usr/bin"

PKG_CONFIG_PATH="/opt/macuim/lib/pkgconfig:/usr/X11R6/lib/pkgconfig" \
LIBS="-Wl,-framework -Wl,CoreFoundation -L${prefix}/lib -framework Carbon" \
CPPFLAGS="-no-cpp-precomp -isystem ${prefix}/include" \
CFLAGS="-Os -funroll-loops -fstrict-aliasing -isysroot /Developer/SDKs/MacOSX10.5.sdk -arch i386 -arch ppc -arch x86_64 -mmacosx-version-min=10.4" \
CAIRO_CFLAGS="-I${prefix}/include/cairo" \
CAIRO_LIBS="-L${prefix}/lib -lcairo -lpixman-1" \
LDFLAGS="-arch i386 -arch ppc -arch x86_64" \
LIBRARY_PATH="${prefix}/lib:/usr/lib" \
./configure --prefix=${prefix} --disable-shared \
  --mandir=${prefix}/share/man --disable-gtk-doc --disable-dependency-tracking \
  --x-includes=/usr/X11R6/include --x-libraries=/usr/X11R6/lib \
  --with-included-modules=yes \
  --with-dynamic-modules=no \
|| exit 1

make -w || exit 1
