#!/bin/sh

#if [ "$1" = "" ]; then
#    echo "Usage: $0 <uim_version>"
#    exit 1
#fi

prefix="/opt/macuim"
top=`pwd`
dest="${top}/../../Package/dest"

if [ ! -d ${prefix}/include ]; then
    sudo mkdir ${prefix}/include
fi
if [ ! -d ${prefix}/lib ]; then
    sudo mkdir ${prefix}/lib
fi

PATH="${prefix}/bin:/bin:/bin:/usr/bin"

PKG_CONFIG_PATH=/usr/X11R6/lib/pkgconfig \
LIBS="-L${prefix}/lib" \
pixman_CFLAGS="-I${prefix}/include/pixman-1" \
pixman_LIBS="-L${prefix}/lib" \
CPPFLAGS="-no-cpp-precomp -isystem ${prefix}/include" \
CFLAGS="-Os -funroll-loops -fstrict-aliasing -isysroot /Developer/SDKs/MacOSX10.5.sdk -arch i386 -arch ppc -arch x86_64 -mmacosx-version-min=10.4" \
LDFLAGS="-arch i386 -arch ppc -arch x86_64" \
LIBRARY_PATH="${prefix}/lib:/usr/lib" \
./configure --prefix=${prefix} --disable-shared \
  --mandir=${prefix}/share/man --disable-gtk-doc --disable-dependency-tracking \
|| exit 1

make -w || exit 1
