#!/bin/sh

prefix="/opt/macuim"
top=`pwd`
dest="${top}/../../Package/dest"

if [ ! -d ${prefix}/include ]; then
    sudo mkdir ${prefix}/include
fi
if [ ! -d ${prefix}/lib ]; then
    sudo mkdir ${prefix}/lib
fi

PATH="${prefix}/bin:/bin:/bin:/usr/bin"

LIBS="-Wl,-framework -Wl,CoreFoundation -L${prefix}/lib" \
CPPFLAGS="-no-cpp-precomp -isystem ${prefix}/include -D_POLL_EMUL_H_" \
CFLAGS="-Os -funroll-loops -fstrict-aliasing -isysroot /Developer/SDKs/MacOSX10.5.sdk -arch i386 -arch ppc -arch x86_64 -mmacosx-version-min=10.4" \
LDFLAGS="-arch i386 -arch ppc -arch x86_64" \
LIBRARY_PATH="${prefix}/lib:/usr/lib" \
./configure --prefix=${prefix} --disable-shared \
  --mandir=${prefix}/share/man --disable-gtk-doc --disable-dependency-tracking \
  --disable-dependency-tracking \
|| exit 1

LIBS="-lintl -liconv -L${prefix}/lib" make -w || exit 1
